server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout: 5s

logging:
  level:
    ROOT: INFO

spring:
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: "foo"
    producer:
      bootstrap-servers:
        - localhost:9092